### ISSUE TITLE
[bug] "Open deployments" link opens the personal vercel page instead of team's page

### ISSUE THREAD

**Issue by GorvGoyl** [aarondill/Vercel-Project-Manager#12]
![screenshot 2024-03-14 at 11 32 08@2x](https://github.com/aarondill/Vercel-Project-Manager/assets/7106086/ff8aa072-fc4d-4fb0-bab8-f2d799977f63)

it opens `https://vercel.com/personal/my_project` instead of the correct one: `https://vercel.com/team/my_project`

**Comment by aarondill** [comment]
When veiwing a team project, what is `/team/` in the URL? is it the team name? the team ID?

**Comment by GorvGoyl** [comment]
it's the team name.

**Comment by aarondill** [comment]
@GorvGoyl Please update your plugin to V2.2.2 and run `Output debugging information`.

If it contains your team's name in the output, could you list the path to get to it `ie: Project information.someKey.teamName`

Note: Do ***NOT*** paste this output here without careful consideration. This output contains a *lot* of identifying and sensitive content, including email addresses, and your access token!

**Comment by GorvGoyl** [comment]
sorry, it's the team url that is needed not the team name. Moreover, team url and team name are not present in the `Output debugging information`

![screenshot 2024-03-14 at 14 15 25@2x](https://github.com/aarondill/Vercel-Project-Manager/assets/7106086/376cc500-7fca-4f51-8eb9-e898b1a89ccf)

**Comment by aarondill** [comment]
@GorvGoyl  is `Project information.accountId` the same value as `User vercel information.id` or `Authentication.teamId`?

**Comment by GorvGoyl** [comment]
Project information.accountId = Authentication.teamId

**Comment by aarondill** [comment]
could you try running this command in your terminal and providing the output? I am not personally a part of a Vercel Team, so I can't access any of the team APIs to inspect their output (docs only say:  `{ "type": "object", "description": "Data representing a Team." }`)

Replace <TEAM_ID> and <TOKEN> with your values from the last line of debug output
```shell
> curl -X GET "https://api.vercel.com/v2/teams/<TEAM_ID>" -H "Authorization: Bearer <TOKEN>" -H "Content-Type: application/json"
```

**Comment by GorvGoyl** [comment]
got below error, I think that access token doesn't have sufficient permission to get data. when I tried with a custom full-scope access token it worked.

`{"error":{"code":"team_unauthorized","message":"You are not authorized"}}%    `

**Comment by aarondill** [comment]
I can't seem to find a way to get the URL for the teams dashboard.
The current implementation is just this:
```ts
    const base = vscode.Uri.parse("https://vercel.com");
    const url = vscode.Uri.joinPath(base, user.username, projectInfo.name);
```
In order to get it to work with teams, we would use `user.username` when `teamId` is `null`, else the team name, but I don't have the team name, and the API doesn't seem to describe a way to get it (other than `/v2/teams` possibly, which just failed`)

[Here's the vercel API docs](https://vercel.com/docs/rest-api/endpoints). If you can find a way to get to the dashboard with the information we are provided (see the debug output) or an API endpoint, I'll be happy to implement this; but I can't do it myself.

**Comment by aarondill** [comment]
> also, could you please update the url to directly land on the deployment page instead of the project home page: `https://....projectname/deployments`
Done

**Comment by aarondill** [comment]
> One simple idea i just had is to offer a vscode setting config where i can mention the team url, and based on the value you can set url.

since I don't have a better solution I suppose i'm going to do this.

**Comment by aarondill** [comment]
Would you try out #15 to see if this fixes the issue?
Note that Dashboard URL should be set to `https://vercel.com/{team}`

**Comment by GorvGoyl** [comment]
hey i can't seem to find the option. 
![screenshot 2024-05-12 at 12 40 44@2x](https://github.com/aarondill/Vercel-Project-Manager/assets/7106086/9c6c52c8-540d-4249-9bdf-7b45a92d86b7)
![screenshot 2024-05-12 at 12 41 55@2x](https://github.com/aarondill/Vercel-Project-Manager/assets/7106086/410d1dfa-1e14-4328-84d3-d7785eea2be5)
![screenshot 2024-05-12 at 12 42 04@2x](https://github.com/aarondill/Vercel-Project-Manager/assets/7106086/5ebf21c3-a2a6-47db-924d-9681a326670c)

**Comment by aarondill** [comment]
@GorvGoyl this is not currently published to the marketplace. you'll have to compile it locally to test it. I don't want to release it until i'm certain of the API.

to compile it, clone the repo and run these commands in order
```shell
> cd PATH_TO_REPO
> git fetch origin pull/12/head:pr_12
> git checkout pr_12
> npm install
> npm run ext:package
> code --install-extension *.vsix
```

**Comment by aarondill** [comment]
@GorvGoyl have you gotten the chance to test that pr after compiling?

**Comment by GorvGoyl** [comment]
@aarondill thanks for the reminder. Just tested and it's working fine :)
