### ISSUE TITLE
Make the status bar ready state date more precise

### ISSUE THREAD

**Issue by ackvf** [aarondill/Vercel-Project-Manager#16]
"last year" that this extension reports is too vague
![image](https://github.com/user-attachments/assets/9f3e31cc-a072-423f-b54a-54863d75088c)

The other extension gives better approximation
![image](https://github.com/user-attachments/assets/f74bef88-5eff-45ee-95da-9817e6e4d2ef)

Last deployment was indeed 6 months ago.
![image](https://github.com/user-attachments/assets/672e4796-27eb-4503-9219-22b2436f26b7)

**Comment by aarondill** [comment]
This is now available on the marketplace. Please update to 2.3.1.
