### ISSUE TITLE
Error upon "Link to Vercel"

### ISSUE THREAD

**Issue by AppreciateIT** [aarondill/Vercel-Project-Manager#2]
I'm getting this error when I try to link to Vercel using VSCode in Windows 10. Any clues or fixes would be appreciated:

(trap "exit $?" INT && clear && echo "Type cmd/ctrl/meta + c to quit" && echo ; if ! command -v vercel &>/dev/null ; then echo "The vercel CLI is required for this feature.

Please install with npm install -g vercel" ; while true; do : ; done ; exit 1 ; fi ; vercel link -t ZE2UIJJplGAZOxW7UkLdaR2P ); ret=$? ; test $ret -eq 130 && exit 0 ; test $ret -eq 0 && exit $ret ; test $ret -nq 0 && exit $ret
ParserError:
Line |
1 | … INT && clear && echo "Type cmd/ctrl/meta + c to quit" && echo ; if ! …
| ~
| Missing closing ')' in expression.
PS C:\Users\mrmat> export PATH=$PWD/node_modules/.bin:$PATH
export: The term 'export' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by aarondill** [comment]
current link, deploy, and dev will not work on windows. I'll need to add this support later when I have time.

**Comment by aarondill** [comment]
This should now be fixed! Feel free to reopen if #3 hasn't fixed your issue
