### ISSUE TITLE
[Feature request] show deployed branch name

### ISSUE THREAD

**Issue by GorvGoyl** [aarondill/Vercel-Project-Manager#6]
It would be nice if I could get a little bit more info like `preview` vs `production` and/or deployed branch name.

![image](https://github.com/aarondill/Vercel-Project-Manager/assets/7106086/5d80005a-3a85-4534-b7cd-bb546fe9b834)

**Comment by aarondill** [comment]
what format would you prefer it in?
i'm thinking something like: `date, time - branch - prod/prev`

**Comment by GorvGoyl** [comment]
I'd prefer imp. info first. Time info at the last since I know it's time-sorted anyway.
ex: `preview/production` - `branch` - `date-time`.
