### ISSUE TITLE
Infinite loading loop after relaunch VS code.

### ISSUE THREAD

**Issue by RutsuKun** [aarondill/Vercel-Project-Manager#8]
![image](https://github.com/aarondill/Vercel-Project-Manager/assets/14915249/6387cebd-366d-4987-9ddc-dd91c4a63fbb)

Reinstalling the plugin fixes this but only temporarily.

**Comment by aarondill** [comment]
As it turns out, the issue was when you opened the Deployments panel before the status bar finished loading the current deployments.

This has been fixed in #9
